//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    class TemperatureConversion
    {
        static double celsius_C;
     static double farhenhit_F;
       
        public void temperaturecoversion()
        {
            Console.WriteLine("enter the option ");

            int temperature = Utility.userInputs();
            switch(temperature)
            {
                case 1:
                    Console.WriteLine("enter the temperature ");

                    farhenhit_F = Utility.userInputs();
                    celsius_C = (farhenhit_F * 9 / 5) + 32;
                    Console.WriteLine("the clesius" + celsius_C);
                    break;
                case 2:
                    Console.WriteLine("enter the temperature");

                    celsius_C = Utility.userInputs();
                    farhenhit_F = (celsius_C - 32) * 5 / 9;
                    Console.WriteLine("the farhenhit" + farhenhit_F);
                    break;


            }


        }
     
    }
}
