//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace DataStructure
{
    class PrimeRange
    { /// <summary>
      /// calling function by creating object for class 
      /// </summary>
        public void Primerange()
        {
           
            int[,] array = new int[10, 100];
            int K = 1;
            bool prime;
            int n = 0;
            for (int loop = 0; loop < 10; loop++)
            {
                for (int loop1 = 0; loop1 < 100; loop1++)
                {
                    array[loop, loop1] = K;
                    K++;
                }

            }


            for (int loop1 = 0; loop1 < 10; loop1++)
            {
                for (int loop = 0; loop < 100; loop++)
                {
                    n = array[loop1, loop];
                    ////calling function to check prime or not 
                    prime = Primecheck(n);
                   
                    //// arranging the array elemnents according to there size compatbility
                    if (prime == true && array[loop1, loop] < 10)
                    {
                        Console.Write(array[loop1, loop] + "  ");
                    }
                    else if (prime == true && array[loop1, loop] < 100)
                    {
                        Console.Write(array[loop1, loop] + " ");
                    }
                    else if (prime == true && array[loop1, loop] > 100)
                    {
                        Console.Write(array[loop1, loop]);
                    }
                    else
                    {
                        Console.Write(" ");

                    }

                }
                ////   Console.WriteLine();
            }
        }
        public bool Primecheck(int n)
        {
            int count = 0;
            for (int index = 1; index < 1000; index++)
            {
                if (n % index == 0)
                {
                    count++;
                }

            }
            if (count == 2)
            {
                return true;
            }
            else
            {
                return false;
            }


        }



    }
}
