//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace DataStructure
{
    class Utility
    {
        /// <summary>
        /// calling function to take integer input
        /// </summary>
        /// <returns></returns>
        public static int IntegerInput()
        {
            return int.Parse(Console.ReadLine());
        }
        /// <summary>
        /// calling function to take string input
        /// </summary>
        /// <returns></returns>
        public static string stringinput()
        {
            return Console.ReadLine();
        }

    }
}
