//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    class Distance
    {
        public  void origintopoint()
        {
            int x = Utility.userInputs();
            int y = Utility.userInputs();
            double distance = Math.Sqrt(x * x + y * y);
            Console.WriteLine("the distance between point (x,y) to (0,0)" + distance);

        }
    }
}
