//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    class ArrayTriplet
    {
        public static void triplets()
        {
         
            int n = Utility.userInputs();
            int[] arr = new int[n];
            for(int i=0;i<n;i++)
            {
                Console.WriteLine("enter the array elements");
                arr[i] = Utility.userInputs();
            }
           Utility.insertelements(arr, n);

        }
    }
}
