//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    class VendingMachine
    {
        public  void CurrencyNotes()
        {
            Console.WriteLine("enter the size of array :");
            int n = Utility.userInputs();
            Console.WriteLine("enter the amount to get notes count: ");
            int amount = Utility.userInputs();
            int[] notes = new int[n];
            int[] Notescounter = new int[n];

            for (int i = 0; i < n; i++)
            {
                Console.WriteLine("enter the currency from 1 to 2000  in array");
                notes[i] = Utility.userInputs();
                if (amount >= notes[i])
                {
                    Notescounter[i] = amount / notes[i];
                    amount = amount - Notescounter[i] * notes[i];
                }
            }

                Console.WriteLine("currency count by vending machine ");
              for (int i = 0; i < n; i++)
              {   
                    if(Notescounter[i] != 0)
                   {
                    Console.WriteLine(notes[i] + "     " + Notescounter[i]);
                    


                    }
              }
                
         }
    }
}
